[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
evm_version = "paris"

remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
op_sepolia = "${OP_SEPOLIA_RPC}"
